# Generated by Django 5.2.6 on 2025-11-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pastry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastry_name', models.CharField(max_length=100)),
                ('pastry_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pastry_category', models.CharField(choices=[('CAKE', 'Cake'), ('BROWNIE', 'Brownie'), ('DOUGHNUT', 'Doughnut'), ('COOKIE', 'Cookie'), ('TART', 'Tart'), ('CUPCAKE', 'Cupcake')], editable=False, max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Pastries',
            },
        ),
    ]
