# Generated by Django 5.2.6 on 2025-11-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastryCustomisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=50)),
                ('filling', models.CharField(blank=True, max_length=50)),
                ('frosting', models.CharField(blank=True, max_length=50)),
                ('layers', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=20)),
                ('decoration', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pastry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastry_name', models.CharField(max_length=100)),
                ('pastry_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pastry_category', models.CharField(choices=[('CAKE', 'Cake'), ('BROWNIE', 'Brownie'), ('DOUGHNUT', 'Doughnut'), ('COOKIE', 'Cookie'), ('TART', 'Tart'), ('CUPCAKE', 'Cupcake')], editable=False, max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Pastries',
            },
        ),
        migrations.CreateModel(
            name='BrownieCustomisation',
            fields=[
                ('pastrycustomisation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pastry.pastrycustomisation')),
                ('chocolate_type', models.CharField(choices=[('DARK', 'Dark Chocolate'), ('MILK', 'Milk Chocolate')], default='DARK', max_length=20)),
                ('texture', models.CharField(choices=[('FUDGY', 'Fudgy'), ('CAKEY', 'Cakey')], default='FUDGY', max_length=20)),
                ('toppings', models.CharField(blank=True, max_length=100)),
                ('box_size', models.CharField(blank=True, choices=[('S', 'Small (4 pieces)'), ('M', 'Medium (8 pieces)'), ('L', 'Large (12 pieces)'), ('BOX', 'Box of 24')], default='M', max_length=20, null=True)),
                ('custom_message', models.CharField(blank=True, max_length=100)),
            ],
            bases=('pastry.pastrycustomisation',),
        ),
        migrations.CreateModel(
            name='CakeCustomisation',
            fields=[
                ('pastrycustomisation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pastry.pastrycustomisation')),
            ],
            bases=('pastry.pastrycustomisation',),
        ),
        migrations.CreateModel(
            name='CookieCustomisation',
            fields=[
                ('pastrycustomisation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pastry.pastrycustomisation')),
                ('chips', models.CharField(choices=[('CHOCOLATE', 'Chocolate Chips'), ('FRUIT', 'Fruit Bits'), ('NUTS', 'Nuts')], default='CHOCOLATE', max_length=30)),
                ('dough_type', models.CharField(choices=[('CHOCOLATE', 'Chocolate'), ('OAT', 'Oat'), ('FRUIT', 'Fruit'), ('PEANUT', 'Peanut Butter')], max_length=50)),
                ('pack_size', models.CharField(choices=[('S', 'Small (6 cookies)'), ('M', 'Medium (12 cookies)'), ('L', 'Large (24 cookies)')], max_length=20)),
            ],
            bases=('pastry.pastrycustomisation',),
        ),
        migrations.CreateModel(
            name='CupcakeCustomisation',
            fields=[
                ('pastrycustomisation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pastry.pastrycustomisation')),
                ('icing_style', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            bases=('pastry.pastrycustomisation',),
        ),
        migrations.CreateModel(
            name='DoughnutCustomisation',
            fields=[
                ('pastrycustomisation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pastry.pastrycustomisation')),
                ('dough_flavour', models.CharField(choices=[('VANILLA', 'Vanilla'), ('CHOCOLATE', 'Chocolate'), ('STRAWBERRY', 'Strawberry')], max_length=50)),
                ('glaze', models.CharField(choices=[('NONE', 'No Glaze'), ('SUGAR', 'Sugar Glaze'), ('CHOCOLATE', 'Chocolate Glaze'), ('CARAMEL', 'Caramel Glaze')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            bases=('pastry.pastrycustomisation',),
        ),
        migrations.CreateModel(
            name='TartCustomisation',
            fields=[
                ('pastrycustomisation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pastry.pastrycustomisation')),
                ('filling_type', models.CharField(choices=[('FRUIT', 'Fruit'), ('CUSTARD', 'Custard'), ('CHOCOLATE', 'Chocolate Filling')], default='FRUIT', max_length=50)),
                ('fruit_choice', models.CharField(blank=True, choices=[('STRAWBERRY', 'Strawberry'), ('LEMON', 'Lemon'), ('MANGO', 'Mango'), ('BLUEBERRY', 'Blueberry')], default='STRAWBERRY', max_length=30, null=True)),
                ('crust_type', models.CharField(choices=[('BUTTER', 'Butter Crust'), ('ALMOND', 'Almond Crust'), ('CHOCOLATE', 'Chocolate Crust')], max_length=50)),
                ('serving', models.CharField(choices=[('S', 'Mini (1 serving)'), ('M', 'Medium (2-3 servings)'), ('L', 'Large (5 servings)')], max_length=20)),
            ],
            bases=('pastry.pastrycustomisation',),
        ),
        migrations.AddField(
            model_name='pastrycustomisation',
            name='pastry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customisation', to='pastry.pastry'),
        ),
    ]
