# Generated by Django 5.2.6 on 2025-11-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pastry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastry_name', models.CharField(max_length=100)),
                ('pastry_category', models.CharField(choices=[('CAKE', 'Cake'), ('BROWNIE', 'Brownie'), ('DONUT', 'Donut'), ('COOKIE', 'Cookie'), ('TART', 'Tart'), ('CUPCAKE', 'Cupcake')], max_length=20)),
                ('pastry_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pastries/')),
                ('is_available', models.BooleanField(default=True)),
                ('flavour', models.CharField(blank=True, max_length=50, null=True)),
                ('filling', models.CharField(blank=True, max_length=50, null=True)),
                ('frosting', models.CharField(blank=True, max_length=50, null=True)),
                ('decoration', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=20, null=True)),
                ('layers', models.IntegerField(blank=True, default=1, null=True)),
                ('cake_message', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='custom_cakes/')),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
    ]
