# Generated by Django 5.2.5 on 2025-11-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastry',
            name='cake_message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pastry',
            name='layers',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='pastry',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
