# Generated by Django 5.2.5 on 2025-11-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry', '0002_pastry_cake_message_pastry_layers_pastry_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastry',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_cakes/'),
        ),
    ]
