# Generated by Django 5.2.6 on 2025-12-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
            },
        ),
    ]
